source 'https://rubygems.org'

ruby '2.2.3'

gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'sinatra'
gem 'rspec-sinatra'
gem 'rspec'
gem 'rake'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rubocop'
gem 'database_cleaner'
gem 'dm-transactions'
